language: julia
os:
  - linux
  - osx
julia:
  - 1.0
addons:
  apt_packages:
    - gfortran
script:
  - julia --project --color=yes -e "import Pkg; Pkg.build(); Pkg.instantiate()"
  - julia --check-bounds=yes --depwarn=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);"
